global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

scrape_configs:  
  - job_name: 'xxx'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'xxx:9100' ]
